# Generated by Django 4.1.5 on 2023-01-20 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_stripe_id_order_payment_intent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_intent',
            new_name='stripe_id',
        ),
    ]
