# Generated by Django 4.1.5 on 2024-02-18 04:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
