# Generated by Django 4.1.5 on 2023-01-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
    ]
