# Generated by Django 4.1.5 on 2023-01-19 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_orderdetail_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='stripe_payment_intent',
            new_name='stripe_id',
        ),
    ]
